.if !defined(_MK_GITHUB_0MP_FREEBSD_PORTS_OVERLAY_SILO_INCLUDED)
_MK_GITHUB_0MP_FREEBSD_PORTS_OVERLAY_SILO_INCLUDED=	yes

_MK_GITHUB_0MP_FREEBSD_PORTS_OVERLAY_SILO_DIR:=	${.PARSEDIR:H}

# Overlay UIDs and GIDs need to be prepended because of the decreasing priority order.
UID_FILES:=	${_MK_GITHUB_0MP_FREEBSD_PORTS_OVERLAY_SILO_DIR}/UIDs ${UID_FILES}
GID_FILES:=	${_MK_GITHUB_0MP_FREEBSD_PORTS_OVERLAY_SILO_DIR}/GIDs ${GID_FILES}

.endif
